name: angavel_${GENERAL_PREFIX}_spa
services:
  spa_angular:
    container_name: angavel_${GENERAL_PREFIX}_spa_angular
    tty: true
    build:
      context: .
      dockerfile: ${AG_MODULE_PATH}/.lib/config/SPA/node/Dockerfile
      args:
        SPA_NODE_VERSION_TAG: ${SPA_NODE_VERSION_TAG}
        SPA_ANGULAR_VERSION: ${SPA_ANGULAR_VERSION}
    ports:
      - ${GENERAL_PORTS_IP}:${SPA_PORT}:4245
    volumes:
      - ${AG_MODULE_PATH}/.lib/config/SPA/node-cmd.sh:/node-cmd.sh
      - ${AG_MODULE_PATH}/environment/${GENERAL_PREFIX}/data/SPA/:/var/www/angular/
    command: "ng serve --port 4245 --host 0.0.0.0"
    environment:
      BUILD_ENV: ${SPA_BUILD_ENV}

networks:
  default:
    external: true
    name: ${AG_NETWORK_NAME}
